### ISSUE TITLE
CabalTool TD - ConfigConnection.ini share with right SQL names

### ISSUE THREAD

**Issue by kajov** [artem-alekseev/cabal_server_ep2#1]
Please share ConfigConnection.ini contents with correct SQL db names assigned
rest of the info is not needed

**Comment by artem-alekseev** [comment]
CabalTool TD Don't work with this database, That's why I made a web admin panel

**Comment by kajov** [comment]
Got it, in forum there was suggested TDChien tool or the BG something tool, both not working properly.

Web app needs improvements overall.

Thank you.
